# Generated by Django 4.2.2 on 2023-06-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_c', models.CharField(max_length=255, verbose_name='Название компании')),
                ('address_c', models.CharField(max_length=150, verbose_name='Адрес компании')),
                ('employees', models.IntegerField(blank=True, null=True, verbose_name='Количество сотрудников')),
                ('is_hunting', models.BooleanField(default=True, verbose_name='Ищет работников')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вакансия')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='оклад')),
                ('description', models.TextField(default='Нет описания', verbose_name='Описание')),
                ('is_relevant', models.BinaryField(default=True, verbose_name='Актуальность')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('contacts', models.CharField(max_length=100, verbose_name='Контакты')),
            ],
        ),
    ]
