# Generated by Django 4.2.2 on 2023-06-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=150)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('is_hunting', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default='Нет описания'),
        ),
    ]
