# Generated by Django 4.2.2 on 2023-07-26 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('full-time', 'Полный рабочий день'), ('part-time', 'Частичная занятость'), ('piecework', 'Сдельная работа')], default='full-time', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='required_experience',
            field=models.PositiveIntegerField(default='123', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
