# Generated by Django 4.2.2 on 2023-06-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_worker_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='salary',
            new_name='w_salary',
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('skills', models.CharField(max_length=100)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
            ],
        ),
    ]
